add option to define custom formatter to serialize version
mtkennerly/dunamai pull request #40
Opened 2022-01-27 17:52 UTC by marnikow

If you want to serialize a version you don't have advanced options. By allowing a formatter the callee can reason about the version object and return a serialized version that fits his preference the best.

2022-01-27 19:12 UTC, mtkennerly requested changes

2022-01-27 19:12 UTC, mtkennerly commented on dunamai/formatters.py
> +def format_pieces_as_pep440(
You could just use the existing `serialize_pep440`. The only difference is that `format_pieces_as_pep440` doesn't call `check_version`, but that shouldn't hurt anything here.

2022-01-27 19:12 UTC, mtkennerly commented on dunamai/formatters.py
> +def pep440_meta(version: Version) -> str:
I don't think we need to have these formatters built-in, so please delete formatters.py. Dunamai handles these most common cases via boolean options in `serialize()`, which is more flexible than having separate functions for just a few specific combinations.

2022-01-28 00:30 UTC, marnikow commented on dunamai/__init__.py
> +    def serialize_with_formatter(
I updated the `serialize` function so that it accepts a callable as well.

2022-01-28 09:34 UTC, mtkennerly approved these changes
Thanks! There's a minor complaint from Mypy, but I can fix that and add some tests after the merge.

To avoid Mypy/etc issues in your other PRs, you can enable the pre-commit hooks by running this: `poetry run pre-commit install`

2022-01-28 09:34 UTC, merged